# Generated by Django 5.1.2 on 2024-11-25 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0002_article'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Article',
        ),
    ]
