# Generated by Django 5.1.2 on 2024-11-26 10:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0004_title_cover_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='pubid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='titles', to='backoffice.publisher'),
        ),
    ]
