# Generated by Django 5.1.2 on 2024-11-26 10:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0005_alter_title_pubid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='title',
            name='pubid',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='backoffice.publisher'),
        ),
    ]
