# Generated by Django 5.1.2 on 2024-12-15 13:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backoffice', '0007_reservation'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='end_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
